### ISSUE TITLE
Exampel on how to use

### ISSUE THREAD

**Issue by martin67** [oxayotl/meikik-project#3]
Could you supply an example how you use it in a thymeleaf template. I have difficulties in how to apply it:
My initial code:

```  
       <div class="col">
            <h3>Text</h3>
            <div th:text="${score.text}"/>
        </div>
``` 
But how would it look with `text:basic` instead?

**Comment by oxayotl** [comment]
It would be : 
```
       <div class="col">
            <h3>Text</h3>
            <div text:basic="${score.text}"/>
        </div>
```
However, people have mentioned to me that the `text:basic` is not very useful and better replaced by the css property whitespace : https://developer.mozilla.org/en-US/docs/Web/CSS/white-space 
So I'm going to retire it for version 1.0, and keep only `text:bbcode`.
I'll add a template usage example in the readme then.
Thanks.
